// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24.12.2025 08:13:06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/plugins/**/*.{js,ts,mjs}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/composables/**/*.{js,ts,mjs}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/utils/**/*.{js,ts,mjs}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pelfox/Desktop/Pelfox - Portfolio/pelfox-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;